### ISSUE TITLE
SQLite converter doesn't merge temporary databases

### ISSUE THREAD

**Issue by RasmusOrsoe** [graphnet-team/graphnet#278]
**Describe the bug**
The SQLite converter does not merge temporary databases, but produces a single database for each file.

**To Reproduce**

1. Run sqlite conversion example 

2. See that no files are merged

**Expected behavior**
The SQLite converter **must** by default produce a single database and preferably delete the many tiny databases. It makes no sense to have n_i3files*sqlite_database. I think this is caused by the default `save_strategy = "1:1"` that is inferred if the user doesn't specify certain arguments. I do think `save_strategy = "1:1"` make sense for parquet conversion, but it makes no sense for the SQLite format.

**Comment by asogaard** [comment]
Have you had a change to look into this @RasmusOrsoe?

**Comment by Aske-Rosted** [comment]
Not quite a minimal example but I thought it might still be worth posting. I generated files using the sqlite converter but had force quit due to time and space constraints therefore not reaching the merging part of the script. I managed to merge the files after the fact by using the script attached.

[merge_sqlite_db_files.txt](https://github.com/graphnet-team/graphnet/files/10000724/merge_sqlite_db_files.txt)
