### ISSUE TITLE
I3FeatureExtractor fails in new version of i3 conversion

### ISSUE THREAD

**Issue by MortenHolmRep** [graphnet-team/graphnet#314]
**Describe the bug**
`I3FeatureExtractor()` cannot be called in the current version of `convert_i3_files.py`

**To Reproduce**
1. Insert `I3FeatureExtractor("<pulsemap>")` into  `examples/convert_i3_files.py` with the other extractor methods.
3. Run script

**Expected behavior**
that the extractor method can be called with a pulsemap, as in the old version.

**Full traceback**
```
Traceback (most recent call last):
  File "/mnt/ceph1-npx/user/mholm/workspace/analyses/moon_pointing_analysis/data/convert_i3_files.py", line 108, in <module>
    main_icecube86(backend)
  File "/mnt/ceph1-npx/user/mholm/workspace/analyses/moon_pointing_analysis/data/convert_i3_files.py", line 61, in main_icecube86
    I3FeatureExtractor(pulsemap=str(args.pulsemaps[0])),
TypeError: Can't instantiate abstract class I3FeatureExtractor with abstract methods __call__
```

**Comment by asogaard** [comment]
Yeah, this is intentional: As the error says, `I3FeatureExtractor` is an abstract class, and I don't this is a recent change. You should use the feature extractor class appropriate to your detector, see [here and below](https://github.com/graphnet-team/graphnet/blob/main/src/graphnet/data/extractors/i3featureextractor.py#L17). The example that you mention also uses `I3FeatureExtractorIceCubeUpgrade`, and has done so for a long time.
