### ISSUE TITLE
Database from I3GenericExtractor not compatible with naming convention compared to the rest of the framework.

### ISSUE THREAD

**Issue by MortenHolmRep** [graphnet-team/graphnet#315]
**Describe the bug**
The extractor `I3GenericExtractor` correctly extracts the data specified. This database is, however, not compatible with the rest of the framework. The training is currently built around the feature list from `constants.features` and `constants.truth`, in the old feature extractor several variables are renamed and one is found via a function. I.e. `position__x`, `position__y`, `...` becomes `dom_x`, `dom_y`, `...`.
`rde` is found using `_get_relative_dom_efficiency(frame, om_key)` and is therefore not in the database resulting from the generic method.

**Expected behavior**
That the generic extractor upholds the naming convention and finds the same variables as those used in constants.

**Comment by RasmusOrsoe** [comment]
1. _"This database is, however, not compatible with the rest of the framework."_
Could you elaborate? The naming convention is different, but the framework (should) allow for this. 
2. _"the old feature extractor several variables are renamed and one is found via a function. I.e. position__x, position__y, ... becomes dom_x, dom_y, ...."_
I'm not sure what you mean here. Are you saying that interaction vertex becomes dom position? Again, renaming should not be an issue, as you can simply specify a new set of feature variable names in the training script.
3. _"rde is found using _get_relative_dom_efficiency(frame, om_key) and is therefore not in the database resulting from the generic method."_
This should be available in there, somewhere. But it might be called something different than what we're used to. Perhaps @asogaard

**Comment by asogaard** [comment]
> **Expected behavior**
That the generic extractor upholds the naming convention and finds the same variables as those used in constants.

That shouldn't be the expected behaviour. The `I3GenericExtractor` will _by design_ produce columns with names that are derived automatically from the I3-file on which it was called. So if you want to train on features extracted in this way, simply specify the feature names yourself [here](https://github.com/graphnet-team/graphnet/blob/main/examples/train_model.py#L33) rather than using the constant features that go with the `I3FeatureExtractor`. We should find a way to make this clearer in the documentation.

Also, the relative dom efficiency _is_ in there somewhere, from [here](https://github.com/graphnet-team/graphnet/blob/main/src/graphnet/data/extractors/utilities/types.py#L240) -- it's called `relative_dom_efficiency` in the unit test data files, and I have added a PR to make this clear in #317 .
