### ISSUE TITLE
Filters and subsection in data 

### ISSUE THREAD

**Issue by MoustHolmes** [graphnet-team/graphnet#386]
Often we want to train on subsection of a dataset like excluding neutral current events or energy’s in a certain range. there should be a way to define simple cuts maybe in the dataset configs and maybe an option to give a path to a list of event_no for more complicated cuts.  is there a simple way to achieve the simple cuts in the current version of the training exaples?.

**Comment by MortenHolmRep** [comment]
Correct me if I am wrong, @MoustHolmes. This issue ties into what I mentioned in one of the previous meetings about changing the database format to include sub-selections in the database. i.e. PID becomes a series of bool as; isNoise, isMuon, etc. or in the case of CC and NC; the interaction_types becomes; isCC, isNC, isGN, etc. A change I am all for.

The data structure in our databases should be changed because the where statement in SQL is slow when filtering across the entire dataset. The alternative is to make our own bool modifications to a dataset and/or run an SQLite query once and save the selection as event numbers that we can give the data loader as a selection. It seems needlessly complex either way.

**Comment by RasmusOrsoe** [comment]
@MoustHolmes I'm not sure i entirely understand what you're asking here. 

The way you select a subsection of your dataset is by providing a selection argument to the `make_dataloader`. A selection is a list of `event_no`'s. There are in-built methods that will calculate some selections for you, but you should be ready to make these selections on your own. 

I'm not too familiar with the new config system, but training with selections work just fine in the training example without configs.

I'm closing the issue - feel free to re-open if I have misunderstood you.

**Comment by asogaard** [comment]
Hi all,

@MoustHolmes , am I understanding you correctly that you would like to see the selection in the `DatasetConfig`s, e.g. [here](https://github.com/graphnet-team/graphnet/blob/main/configs/datasets/training_example_data_parquet.yml#L40), be more fully-featured, to allow for 

1. simple selections, like energy truth-level cuts or PID selection, and
2. providing a path to CSV-files containing event indices resulting from a more involved event selection, that doesn't lend itself to such a simple, query-like syntax.

If so, I think this sounds like a very nice addition. I'm on it.
