### ISSUE TITLE
Prediction dataloader does not make of use multiple GPU's like train/validation dataloader does.

### ISSUE THREAD

**Issue by Aske-Rosted** [graphnet-team/graphnet#425]
**Describe the bug**
Running a training/validation followed by a prediction, with multiple GPU's the training and validation runs will use the requested GPU's however the prediction run will not. 

**To Reproduce**
Run the 01_Train_model.py Example script
Observe the GPU usage using GPU monitoring such as nvitop.

**Expected behavior**
Expect for the prediction run to also make use of the multiple GPU'S.

**Full traceback**
No error message unless your batch exceeds the memory available to a single GPU while being within the bounds of the shared GPU memory. 

**Additional context**
Since Batching is handled different when running on multiple compared to single GPU this can give errors when running a script which has training and validation followed by prediction with the exact same configurations

**Comment by asogaard** [comment]
This is intentional: Running predictions with multiple GPUs will result in predictions that are split across multiple devices. Instead of trying to merge these (you're welcome to give it a shot), we have opted for forcing single-GPU predictions. The reasoning is that training is _much_ more compute intensive than predictions, and therefore the downside to making this choice should be rather small. But you're welcome to open a feature request for multi-GPU predictions.
