### ISSUE TITLE
Runtime error when using example_direction_reconstruction config file.

### ISSUE THREAD

**Issue by AMHermansen** [graphnet-team/graphnet#570]
**Describe the bug**
When trying to run `examples/04_training/01_train_model.py` with the model config `example_direction_reconstruction.yml` you get a runtime error.

**To Reproduce**
1. perform clean installation of GraphNeT.
2. use command `python /path/to/examples/04_training/01_train_model.py --model-config /path/to/configs/models/example_direction_reconstruction_model.yml`

**Expected behavior**
I would expect the training script to work with any of the provided example config files, and give prediction for the direction.

**Full traceback**
```
Traceback (most recent call last):
  File "examples/04_training/01_train_model.py", line 177, in <module>
    main(
  File "examples/04_training/01_train_model.py", line 119, in main
    results = model.predict_as_dataframe(
  File "/home/andreas/Documents/Coding/GitHub/dev/graphnet/src/graphnet/models/standard_model.py", line 207, in predict_as_dataframe
    return super().predict_as_dataframe(
  File "/home/andreas/Documents/Coding/GitHub/dev/graphnet/src/graphnet/models/model.py", line 223, in predict_as_dataframe
    assert len(prediction_columns) == predictions.shape[1], (
AssertionError: Number of provided column names (2) and number of output columns (4) don't match.

```

**Additional context**
I believe the bug is a result of how the `prediction_columns` are created at line 106-114 in `01_train_model.py`. They only create one column, for each task, however some of the directional tasks produce multiple output columns (multiple directions or kappa for various VonMisesFisher)

**Comment by RasmusOrsoe** [comment]
Thanks for pointing this out @AMHermansen . We should actually remove `prediction_columns` as argument to `predict_as_dataframe` in the example (not in general), because if the argument is `None`, the method will automatically find the right column names via the model property `my_model.prediction_labels`. Could you try and see if that solves the problem?

**Comment by AMHermansen** [comment]
Thank you @RasmusOrsoe, removing `prediction_columns` stopped the error. For a future PR how much should be removed, the entire argument in the CLI, or just the keyword-argument being passed to `predict_as_dataframe`? In #576 I have added some code, which would prevent a runtime error like this. I believe it is a poor time to crash during `predict_as_dataframe`, since it is usually called near the very end of an example script.

**Comment by RasmusOrsoe** [comment]
Great to hear it worked. I think a PR fixing this should just: 
1. Remove all references to `prediction_columns` in the training example. (Including CLI). It makes the code simpler.

As for #576 - I'm not a fan of changing the `prediction_columns` ad-hoc to make dimensions fit. I think the proper way of handling this is to throw an error - which is what the code currently does. We could update the error message to make it more informative, but otherwise I'd prefer to keep it as-is. If we really wanted to make this nice, we could make a PR where

1. `Model.Predict` is changed such that it toggles between two behaviors: **a)** Inference on a full dataloader (current functionality), **b)**: Inference on a single batch.

**Comment by AMHermansen** [comment]
I just don't like raising an avoidable error just before saving everything to disk. This could cause time to be wasted for large trainings, where at best you would need to hope the model is saved at some checkpoint to a lightning-log. And at worst you have to do the entire training again.

Moving the `predict_as_dataframe` down after saving the model related files, including a try-except statement around `predict_as_dataframe`, or include a test for dimensionality at the beginning (before training has started).

**Comment by RasmusOrsoe** [comment]
@AMHermansen I'm fine with moving the `predict_as_dataframe` to after the model saving. :-)
