### ISSUE TITLE
Do we need to include graph_definition in both data and model config files?

### ISSUE THREAD

**Issue by AMHermansen** [graphnet-team/graphnet#582]
Currently we require to have the graph_definition in both the data and model config files. This is an error prone approach, since we might make changes in one, but not the other.

Would it be possible to have a separate single config file for the graph definition, that both the dataset and models need to get during construction?

**Comment by RasmusOrsoe** [comment]
The idea with the config files is to summarize decisions that was made; to be able to re-create classes with the same arguments that they were initially instantiated with in a new session. They are essential to the reproducibility philosophy of graphnet.

Specifically for the Dataset class, since it depends on the GraphDefinition argument, I think it makes a lot of sense to write this into the config file, otherwise the class is not fully summarized.

Could you elaborate on how you find this to be error prone?

**Comment by AMHermansen** [comment]
When you have to insert the same values into multiple places human error is bound to happen at some point or another. (You could make a slight typo in one of the config files or forget to update some value.)

I completely agree with having reproducibility, which is why I think it would be more elegant to have a separate config-file containing the `GraphDefinition` class. This new config file, would the be passed to both the Dataset and GNN. An entire run, would then be summarized by 3 config files (Dataset, GraphDefinition, Model) instead of the two config files currently used (Dataset, Model).

**Comment by RasmusOrsoe** [comment]
Thanks for the clarification!

_When you have to insert the same values into multiple places human error is bound to happen at some point or another. (You could make a slight typo in one of the config files or forget to update some value.)_

I agree that programming through the config files can easily lead to mistakes; and I'd like to iterate that this is not the intend of the config files. They exist as a tool to reproduce what was done in the past - not to configure what you'd like to do in the future. Intended use is to use native python code to produce your classes. 

_This new config file, would the be passed to both the Dataset and GNN. An entire run, would then be summarized by 3 config files (Dataset, GraphDefinition, Model) instead of the two config files currently used (Dataset, Model)._

The dataset config would not fully summarize what was done in the session if it does not contain an argument for GraphDefinition. So I fear that splitting the configs into three instead of two will only complicate things further. 

If you'd like to be able to load in a previous dataset from a config file, and then change the GraphDefinition, we could add a class method that overwrites an instantiated Dataset's GraphDefinition, e.g. `Dataset.change_graph_definition(new_graph_definition)`. Would that work for you?
