### ISSUE TITLE
Evaluate KNN-graph alternatives

### ISSUE THREAD

**Issue by RasmusOrsoe** [graphnet-team/graphnet#64]
Covers both whether to include empty DOMs, and if so which ones, as well as how to connect the DOMs that are included.

**Comment by asogaard** [comment]
This is a somewhat extensive issue. It might be better to break it down into constituent tasks, similar to #91, in order to make these easier for newcomers to get started on. What do you think, @RasmusOrsoe? Also, it is related to the "Performance paper" project, but I figure we won't be doing any further model optimisation/tuning for the low-energy performance paper — so should we move it to the "Version 1.0.0" project instead?
